In [1]:
# Imports
import pandas as pd

In [2]:
# Read CSV file
aqi_df = pd.read_csv('annual_aqi_by_cbsa_2022.csv')

# Display first 5 rows
aqi_df.head()

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
0,"Aberdeen, SD",10100,2022,177,174,3,0,0,0,0,66,33,18,0,0,0,96,81
1,"Aberdeen, WA",10140,2022,212,211,1,0,0,0,0,63,23,14,0,0,0,212,0
2,"Ada, OK",10220,2022,61,50,11,0,0,0,0,90,58,44,0,0,45,16,0
3,"Adrian, MI",10300,2022,181,146,35,0,0,0,0,97,62,39,0,0,104,77,0
4,"Akron, OH",10420,2022,253,191,58,3,1,0,0,159,66,43,0,0,162,91,0

In [3]:
# Split CBSA column into 'City' and 'State'
aqi_df[['City', 'State']] = aqi_df['CBSA'].str.split(',', expand=True)

# Drop CBSA column
aqi_df.drop('CBSA', axis=1, inplace=True)

# Display first 5 rows
aqi_df

,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
0,10100,2022,177,174,3,0,0,0,0,66,33,18,0,0,0,96,81,Aberdeen,SD
1,10140,2022,212,211,1,0,0,0,0,63,23,14,0,0,0,212,0,Aberdeen,WA
2,10220,2022,61,50,11,0,0,0,0,90,58,44,0,0,45,16,0,Ada,OK
3,10300,2022,181,146,35,0,0,0,0,97,62,39,0,0,104,77,0,Adrian,MI
4,10420,2022,253,191,58,3,1,0,0,159,66,43,0,0,162,91,0,Akron,OH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,49420,2022,212,164,46,2,0,0,0,109,63,29,0,0,0,210,2,Yakima,WA
492,49620,2022,298,230,67,1,0,0,0,105,61,40,0,57,101,140,0,York-Hanover,PA
493,49660,2022,243,186,53,4,0,0,0,136,61,43,0,0,183,60,0,Youngstown-Warren-Boardman,OH-PA
494,49700,2022,181,116,64,1,0,0,0,102,76,46,0,0,107,74,0,Yuba City,CA
495,49740,2022,273,169,95,9,0,0,0,142,80,46,0,0,173,32,68,Yuma,AZ

In [7]:
# Obtain 'North Carolina' data
nc_df = aqi_df.loc[aqi_df['State'] == ' NC']

# Display first 5 rows
nc_df.head()

,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
19,11700,2022,273,227,45,1,0,0,0,108,58,43,0,0,205,68,0,Asheville,NC
130,20500,2022,273,246,27,0,0,0,0,93,50,41,0,0,201,72,0,Durham-Chapel Hill,NC
154,22180,2022,273,219,53,1,0,0,0,115,60,41,0,0,201,69,3,Fayetteville,NC
182,24660,2022,273,214,59,0,0,0,0,84,57,43,0,0,187,84,2,Greensboro-High Point,NC
183,24780,2022,273,255,18,0,0,0,0,97,48,37,0,0,203,70,0,Greenville,NC

In [8]:
# Obatin Cities in North Carolina
nc_df['City'].unique()

array(['Asheville', 'Durham-Chapel Hill', 'Fayetteville',
       'Greensboro-High Point', 'Greenville', 'Hickory-Lenoir-Morganton',
       'Kinston', 'Morehead City', 'Oxford', 'Raleigh', 'Roanoke Rapids',
       'Rocky Mount', 'Wilmington', 'Winston-Salem'], dtype=object)