In [1]:
import pandas as pd

In [3]:
# Create Data Frame
annual_aqi_df = pd.DataFrame()

# Obatin csv files
csv_files = []
for x in range(0, 10):
    name = f"Resources/annual_aqi_by_county_200{x}.csv"
    csv_files.append(name)

for x in range(10, 23):
    name = f"Resources/annual_aqi_by_county_20{x}.csv"
    csv_files.append(name)
    
for x in range(80, 100):
    name = f"Resources/annual_aqi_by_county_19{x}.csv"
    csv_files.append(name)

# Append all files together
for file in csv_files:
            df_temp = pd.read_csv(file)
            annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)

C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)
C:\Users\arian\AppData\Local\Temp\ipykernel_2064\966517947.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  annual_aqi_df = annual_aqi_df.append(df_temp, ignore_index=True)

In [4]:
# View Data Frame
annual_aqi_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
0,Alabama,Baldwin,2000,257,111,96,39,10,1,0,205,129,54,0,0,215,42,0
1,Alabama,Clay,2000,271,155,101,14,1,0,0,177,90,46,0,0,188,83,0
2,Alabama,Colbert,2000,106,38,66,2,0,0,0,124,80,58,0,0,0,106,0
3,Alabama,DeKalb,2000,354,169,123,58,4,0,0,159,115,51,0,0,297,56,1
4,Alabama,Elmore,2000,242,125,78,37,2,0,0,166,112,50,0,0,242,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39507,Wyoming,Platte,1999,60,60,0,0,0,0,0,42,30,13,0,0,0,0,60
39508,Wyoming,Sheridan,1999,283,225,58,0,0,0,0,98,59,31,0,0,0,101,182
39509,Wyoming,Sublette,1999,361,204,150,7,0,0,0,126,74,48,0,0,360,1,0
39510,Wyoming,Sweetwater,1999,63,58,5,0,0,0,0,63,48,26,0,0,0,0,63
39511,Wyoming,Teton,1999,355,256,95,4,0,0,0,126,68,45,0,0,351,2,2

In [5]:
# Set 'State' to index
annual_aqi_df = annual_aqi_df.set_index("State")

annual_aqi_df.head()

,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
State,,,,,,,,,,,,,,,,,
Alabama,Baldwin,2000,257,111,96,39,10,1,0,205,129,54,0,0,215,42,0
Alabama,Clay,2000,271,155,101,14,1,0,0,177,90,46,0,0,188,83,0
Alabama,Colbert,2000,106,38,66,2,0,0,0,124,80,58,0,0,0,106,0
Alabama,DeKalb,2000,354,169,123,58,4,0,0,159,115,51,0,0,297,56,1
Alabama,Elmore,2000,242,125,78,37,2,0,0,166,112,50,0,0,242,0,0

In [6]:
# Obtain NC data
nc_aqi_df = annual_aqi_df.loc[["North Carolina"]]
nc_aqi_df

,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
State,,,,,,,,,,,,,,,,,
North Carolina,Alamance,2000,104,37,66,1,0,0,0,104,76,56,0,0,0,104,0
North Carolina,Alexander,2000,211,94,64,48,5,0,0,182,126,58,0,0,211,0,0
North Carolina,Avery,2000,365,211,117,34,3,0,0,172,101,47,0,0,353,12,0
North Carolina,Buncombe,2000,260,129,110,15,6,0,0,179,93,51,0,0,176,84,0
North Carolina,Cabarrus,2000,115,36,78,1,0,0,0,118,86,56,0,0,0,114,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
North Carolina,Swain,1999,257,116,128,13,0,0,0,140,93,54,0,0,173,82,2
North Carolina,Union,1999,188,95,53,27,13,0,0,187,133,50,0,0,188,0,0
North Carolina,Wake,1999,363,134,156,41,23,9,0,220,143,58,21,0,161,181,0
North Carolina,Wayne,1999,110,54,51,5,0,0,0,117,83,52,0,0,0,93,17
North Carolina,Yancey,1999,179,41,93,35,10,0,0,185,133,74,0,0,179,0,0

In [7]:
# Save Data Frame as new csv
nc_aqi_df.to_csv('Resources/nc_aqi_1980-2022.csv')